-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 14:55:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `answers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `answers_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `is_right` TINYINT NULL,
  `questions_id` INT NOT NULL,
  `questions_answers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `is_right`, `questions_id`, `questions_answers_id`),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questions_id` , `questions_answers_id`)
    REFERENCES `mydb`.`questions` (`id` , `answers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `id` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_has_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_has_questions` (
  `test_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  `questions_answers_id` INT NOT NULL,
  PRIMARY KEY (`test_id`, `questions_id`, `questions_answers_id`),
  CONSTRAINT `fk_test_has_questions_test`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_questions_questions1`
    FOREIGN KEY (`questions_id` , `questions_answers_id`)
    REFERENCES `mydb`.`questions` (`id` , `answers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_has_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_has_students` (
  `test_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`test_id`, `students_id`),
  CONSTRAINT `fk_test_has_students_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_students_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_answers_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_answers_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tests_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  `answers_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tests_id`, `students_id`, `answers_id`, `questions_id`),
  CONSTRAINT `fk_student_answers_test_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `mydb`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_answers_test_test1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `mydb`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_answers_test_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_answers_test_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `mydb`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
